using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ClassicUO.SourceGenerators
{
    [Generator]
    public class SqlSettingGenerator : IIncrementalGenerator
    {
        private const string AttributeSource = @"// <auto-generated/>
using System;

namespace ClassicUO.Configuration
{
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class SqlSettingAttribute : Attribute
    {
        public SqlSettingAttribute(SettingsScope scope, string key, object defaultValue = null)
        {
            Scope = scope;
            Key = key;
            DefaultValue = defaultValue;
        }

        public SettingsScope Scope { get; }
        public string Key { get; }
        public object DefaultValue { get; }
    }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
                ctx.AddSource("SqlSettingAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            IncrementalValuesProvider<SqlSettingModel> properties = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "ClassicUO.Configuration.SqlSettingAttribute",
                    predicate: static (node, _) => node is PropertyDeclarationSyntax,
                    transform: static (ctx, _) => GetModel(ctx))
                .Where(static m => m != null);

            context.RegisterSourceOutput(properties.Collect(), Generate);
        }

        private static SqlSettingModel GetModel(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not IPropertySymbol prop)
                return null;

            INamedTypeSymbol containingType = prop.ContainingType;
            if (containingType?.Name != "Profile")
                return null;

            AttributeData attr = ctx.Attributes[0];
            if (attr.ConstructorArguments.Length < 3)
                return null;

            // Argument 0: SettingsScope enum value (int ordinal)
            if (attr.ConstructorArguments[0].Value is not int scopeOrdinal)
                return null;

            // Argument 1: key string
            if (attr.ConstructorArguments[1].Value is not string key)
                return null;

            // Argument 2: default value (typed constant, boxed)
            object defaultRaw = attr.ConstructorArguments[2].Value;

            string typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            string fullTypeName = prop.Type.SpecialType != SpecialType.None
                ? GetPrimitiveTypeName(prop.Type.SpecialType)
                : typeName;

            if (!IsSupportedType(fullTypeName))
            {
                return new SqlSettingModel
                {
                    PropertyName = prop.Name,
                    TypeName = fullTypeName,
                    ScopeOrdinal = scopeOrdinal,
                    Key = key,
                    DefaultValueLiteral = "default",
                    ContainingNamespace = containingType.ContainingNamespace?.ToDisplayString() ?? "ClassicUO.Configuration",
                    IsUnsupportedType = true
                };
            }

            string defaultLiteral = BuildDefaultLiteral(fullTypeName, defaultRaw);

            return new SqlSettingModel
            {
                PropertyName = prop.Name,
                TypeName = fullTypeName,
                ScopeOrdinal = scopeOrdinal,
                Key = key,
                DefaultValueLiteral = defaultLiteral,
                ContainingNamespace = containingType.ContainingNamespace?.ToDisplayString() ?? "ClassicUO.Configuration",
                IsUnsupportedType = false
            };
        }

        private static string GetPrimitiveTypeName(SpecialType st)
        {
            switch (st)
            {
                case SpecialType.System_Boolean: return "bool";
                case SpecialType.System_Int32:   return "int";
                case SpecialType.System_UInt32:  return "uint";
                case SpecialType.System_Int16:   return "short";
                case SpecialType.System_UInt16:  return "ushort";
                case SpecialType.System_Single:  return "float";
                case SpecialType.System_Double:  return "double";
                case SpecialType.System_String:  return "string";
                default:                         return null;
            }
        }

        private static bool IsSupportedType(string typeName)
        {
            if (typeName == null) return false;
            switch (typeName)
            {
                case "bool":
                case "int":
                case "uint":
                case "short":
                case "ushort":
                case "float":
                case "double":
                case "string":
                    return true;
                default:
                    return false;
            }
        }

        private static string BuildDefaultLiteral(string typeName, object value)
        {
            if (value == null)
            {
                if (typeName == "string") return "null";
                return GetTypeDefault(typeName);
            }

            switch (typeName)
            {
                case "bool":   return (bool)value ? "true" : "false";
                case "float":  return ((float)(double)value).ToString("R") + "f";
                case "double": return ((double)value).ToString("R") + "d";
                case "string": return "\"" + value.ToString().Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
                default:       return value.ToString();
            }
        }

        private static string GetTypeDefault(string typeName)
        {
            switch (typeName)
            {
                case "bool":   return "false";
                case "string": return "null";
                default:       return "0";
            }
        }

        // Map scope ordinal to SettingsScope name: Char=0, Account=1, Server=2, Global=3
        private static string ScopeName(int ordinal)
        {
            switch (ordinal)
            {
                case 0:  return "Char";
                case 1:  return "Account";
                case 2:  return "Server";
                case 3:  return "Global";
                default: return "Global";
            }
        }

        private static string TryParseExpr(string typeName, string varName, string rawVar)
        {
            switch (typeName)
            {
                case "bool":   return $"bool.TryParse({rawVar}, out bool {varName})";
                case "int":    return $"int.TryParse({rawVar}, out int {varName})";
                case "uint":   return $"uint.TryParse({rawVar}, out uint {varName})";
                case "short":  return $"short.TryParse({rawVar}, out short {varName})";
                case "ushort": return $"ushort.TryParse({rawVar}, out ushort {varName})";
                case "float":  return $"float.TryParse({rawVar}, out float {varName})";
                case "double": return $"double.TryParse({rawVar}, out double {varName})";
                case "string": return null; // no TryParse needed
                default:       return null;
            }
        }

        private static bool IsNonDefaultValue(string typeName, string literal)
        {
            switch (typeName)
            {
                case "bool":   return literal == "true";
                case "string": return literal != "null" && literal != "\"\"";
                default:       return literal != "0" && literal != "0f" && literal != "0d";
            }
        }

        private static void Generate(SourceProductionContext spc, ImmutableArray<SqlSettingModel> models)
        {
            if (models.IsDefaultOrEmpty)
                return;

            // Report diagnostics for unsupported types
            foreach (SqlSettingModel m in models.Where(x => x.IsUnsupportedType))
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "CUOSG003",
                        "Unsupported SQL setting type",
                        $"Property '{m.PropertyName}' has unsupported type '{m.TypeName}' for [SqlSetting].",
                        "ClassicUO.SourceGenerators",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    Location.None));
            }

            var valid = models.Where(x => !x.IsUnsupportedType).ToImmutableArray();
            if (valid.IsEmpty)
                return;

            // Check for duplicate scope+key
            var seen = new HashSet<string>();
            foreach (SqlSettingModel m in valid)
            {
                string combo = $"{m.ScopeOrdinal}:{m.Key}";
                if (!seen.Add(combo))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "CUOSG004",
                            "Duplicate SQL setting key",
                            $"Duplicate key '{m.Key}' in scope '{ScopeName(m.ScopeOrdinal)}' on property '{m.PropertyName}'.",
                            "ClassicUO.SourceGenerators",
                            DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        Location.None));
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text.Json.Serialization;");
            sb.AppendLine("using ClassicUO.Game;");
            sb.AppendLine("using ClassicUO.Game.Managers;");
            sb.AppendLine();
            sb.AppendLine("namespace ClassicUO.Configuration");
            sb.AppendLine("{");
            sb.AppendLine("    public sealed partial class Profile");
            sb.AppendLine("    {");

            // Properties
            foreach (SqlSettingModel m in valid)
            {
                string scopeName = ScopeName(m.ScopeOrdinal);
                sb.AppendLine($"        public partial {m.TypeName} {m.PropertyName}");
                sb.AppendLine("        {");
                sb.AppendLine("            get;");
                sb.AppendLine("            set");
                sb.AppendLine("            {");
                sb.AppendLine("                if (field != value)");
                sb.AppendLine("                {");
                sb.AppendLine($"                    _ = Client.Settings.SetAsync(SettingsScope.{scopeName}, \"{m.Key}\", value);");
                sb.AppendLine("                    field = value;");
                sb.AppendLine("                    OnPropertyChanged();");
                sb.AppendLine("                }");
                sb.AppendLine("            }");

                if (IsNonDefaultValue(m.TypeName, m.DefaultValueLiteral))
                    sb.AppendLine($"        }} = {m.DefaultValueLiteral};");
                else
                    sb.AppendLine("        }");

                sb.AppendLine();
            }

            // Group by scope ordinal
            var byScope = valid.GroupBy(m => m.ScopeOrdinal).ToDictionary(g => g.Key, g => g.ToList());

            // Global / Account / Server: bulk dict load
            foreach (int scopeOrdinal in new[] { 3, 1, 2 }) // Global, Account, Server
            {
                if (!byScope.TryGetValue(scopeOrdinal, out List<SqlSettingModel> group))
                    continue;

                string scopeName = ScopeName(scopeOrdinal);
                sb.AppendLine($"        internal void LoadGenerated{scopeName}SqlSettings(System.Collections.Generic.Dictionary<string, string> kvp)");
                sb.AppendLine("        {");

                foreach (SqlSettingModel m in group)
                {
                    string rawVar = $"_raw_{m.PropertyName}";
                    string tryParse = TryParseExpr(m.TypeName, $"_v_{m.PropertyName}", rawVar);
                    if (tryParse == null)
                    {
                        // string: direct assign
                        sb.AppendLine($"            if (kvp.TryGetValue(\"{m.Key}\", out string {rawVar}))");
                        sb.AppendLine($"                {m.PropertyName} = {rawVar};");
                    }
                    else
                    {
                        sb.AppendLine($"            if (kvp.TryGetValue(\"{m.Key}\", out string {rawVar}) && {tryParse})");
                        sb.AppendLine($"                {m.PropertyName} = _v_{m.PropertyName};");
                    }
                }

                sb.AppendLine("        }");
                sb.AppendLine();
            }

            // Char: individual async loads
            if (byScope.TryGetValue(0, out List<SqlSettingModel> charGroup))
            {
                sb.AppendLine("        internal void LoadGeneratedCharSqlSettings()");
                sb.AppendLine("        {");
                foreach (SqlSettingModel m in charGroup)
                {
                    sb.AppendLine($"            _ = Client.Settings.GetAsyncOnMainThread(SettingsScope.Char, \"{m.Key}\", {m.DefaultValueLiteral}, _v => {{ {m.PropertyName} = _v; }});");
                }
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("Profile.SqlSettings.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    internal class SqlSettingModel
    {
        public string PropertyName { get; set; }
        public string TypeName { get; set; }
        public int ScopeOrdinal { get; set; }
        public string Key { get; set; }
        public string DefaultValueLiteral { get; set; }
        public string ContainingNamespace { get; set; }
        public bool IsUnsupportedType { get; set; }
    }
}
